
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vboxMain;
	
	private global::Gtk.HButtonBox hbuttonboxMenu;
	
	private global::Gtk.Button buttonUpdate;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vboxUsers;
	
	private global::Gtk.Label labelUsers;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.NodeView nodeviewUsers;
	
	private global::Gtk.HButtonBox hbuttonboxUsers;
	
	private global::Gtk.Button buttonUserAdd;
	
	private global::Gtk.Button buttonUserEdit;
	
	private global::Gtk.Button buttonUserDelete;
	
	private global::Gtk.VBox vboxUserEdit;
	
	private global::Gtk.Label labelID;
	
	private global::Gtk.Entry entryUserEditID;
	
	private global::Gtk.Label labelUsername;
	
	private global::Gtk.Entry entryUserEditUsername;
	
	private global::Gtk.Label labelEmail;
	
	private global::Gtk.Entry entryUserEditEmail;
	
	private global::Gtk.Label labelPassword;
	
	private global::Gtk.Entry entryUserEditPassword;
	
	private global::Gtk.HButtonBox hbuttonboxUserEdit;
	
	private global::Gtk.Button buttonUserEditCancel;
	
	private global::Gtk.Button buttonUserEditOK;
	
	private global::Gtk.VBox vboxPosts;
	
	private global::Gtk.Label labelPosts;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.NodeView nodeviewPosts;
	
	private global::Gtk.HButtonBox hbuttonboxPosts;
	
	private global::Gtk.Button buttonPostAdd;
	
	private global::Gtk.Button buttonPostEdit;
	
	private global::Gtk.Button buttonPostDelete;
	
	private global::Gtk.VBox vboxPostEdit;
	
	private global::Gtk.Label labelID1;
	
	private global::Gtk.Entry entryPostEditID;
	
	private global::Gtk.Label labelAuthorID;
	
	private global::Gtk.Entry entryPostEditAuthor;
	
	private global::Gtk.Label labelPostEditTags;
	
	private global::Gtk.Entry entryPostEditTags;
	
	private global::Gtk.Label labelTitle;
	
	private global::Gtk.Entry entryPostEditTitle;
	
	private global::Gtk.Label labelText;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	
	private global::Gtk.TextView textviewPostEditText;
	
	private global::Gtk.HButtonBox hbuttonboxPostEdit;
	
	private global::Gtk.Button buttonPostEditCancel;
	
	private global::Gtk.Button buttonPostEditOK;
	
	private global::Gtk.VBox vboxTags;
	
	private global::Gtk.Label labelTags;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.NodeView nodeviewTags;
	
	private global::Gtk.HButtonBox hbuttonboxTags;
	
	private global::Gtk.Button buttonTagAdd;
	
	private global::Gtk.Button buttonTagEdit;
	
	private global::Gtk.Button buttonTagDelete;
	
	private global::Gtk.VBox vboxTagEdit;
	
	private global::Gtk.Label labelID2;
	
	private global::Gtk.Entry entryTagEditID;
	
	private global::Gtk.Label labelTitle1;
	
	private global::Gtk.Entry entryTagEditTitle;
	
	private global::Gtk.HButtonBox hbuttonboxTagEdit;
	
	private global::Gtk.Button buttonTagEditCancel;
	
	private global::Gtk.Button buttonTagEditOK;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Database Client");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(10));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vboxMain = new global::Gtk.VBox ();
		this.vboxMain.Name = "vboxMain";
		this.vboxMain.Spacing = 6;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.hbuttonboxMenu = new global::Gtk.HButtonBox ();
		this.hbuttonboxMenu.Name = "hbuttonboxMenu";
		// Container child hbuttonboxMenu.Gtk.ButtonBox+ButtonBoxChild
		this.buttonUpdate = new global::Gtk.Button ();
		this.buttonUpdate.CanFocus = true;
		this.buttonUpdate.Name = "buttonUpdate";
		this.buttonUpdate.UseStock = true;
		this.buttonUpdate.UseUnderline = true;
		this.buttonUpdate.Label = "gtk-refresh";
		this.hbuttonboxMenu.Add (this.buttonUpdate);
		global::Gtk.ButtonBox.ButtonBoxChild w1 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxMenu [this.buttonUpdate]));
		w1.Expand = false;
		w1.Fill = false;
		this.vboxMain.Add (this.hbuttonboxMenu);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hbuttonboxMenu]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vboxUsers = new global::Gtk.VBox ();
		this.vboxUsers.Name = "vboxUsers";
		this.vboxUsers.Spacing = 6;
		// Container child vboxUsers.Gtk.Box+BoxChild
		this.labelUsers = new global::Gtk.Label ();
		this.labelUsers.Name = "labelUsers";
		this.labelUsers.LabelProp = global::Mono.Unix.Catalog.GetString ("Users");
		this.vboxUsers.Add (this.labelUsers);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxUsers [this.labelUsers]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vboxUsers.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nodeviewUsers = new global::Gtk.NodeView ();
		this.nodeviewUsers.CanFocus = true;
		this.nodeviewUsers.Name = "nodeviewUsers";
		this.GtkScrolledWindow.Add (this.nodeviewUsers);
		this.vboxUsers.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxUsers [this.GtkScrolledWindow]));
		w5.Position = 1;
		// Container child vboxUsers.Gtk.Box+BoxChild
		this.hbuttonboxUsers = new global::Gtk.HButtonBox ();
		this.hbuttonboxUsers.Name = "hbuttonboxUsers";
		// Container child hbuttonboxUsers.Gtk.ButtonBox+ButtonBoxChild
		this.buttonUserAdd = new global::Gtk.Button ();
		this.buttonUserAdd.CanFocus = true;
		this.buttonUserAdd.Name = "buttonUserAdd";
		this.buttonUserAdd.UseStock = true;
		this.buttonUserAdd.UseUnderline = true;
		this.buttonUserAdd.Label = "gtk-add";
		this.hbuttonboxUsers.Add (this.buttonUserAdd);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxUsers [this.buttonUserAdd]));
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbuttonboxUsers.Gtk.ButtonBox+ButtonBoxChild
		this.buttonUserEdit = new global::Gtk.Button ();
		this.buttonUserEdit.CanFocus = true;
		this.buttonUserEdit.Name = "buttonUserEdit";
		this.buttonUserEdit.UseStock = true;
		this.buttonUserEdit.UseUnderline = true;
		this.buttonUserEdit.Label = "gtk-edit";
		this.hbuttonboxUsers.Add (this.buttonUserEdit);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxUsers [this.buttonUserEdit]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbuttonboxUsers.Gtk.ButtonBox+ButtonBoxChild
		this.buttonUserDelete = new global::Gtk.Button ();
		this.buttonUserDelete.CanFocus = true;
		this.buttonUserDelete.Name = "buttonUserDelete";
		this.buttonUserDelete.UseStock = true;
		this.buttonUserDelete.UseUnderline = true;
		this.buttonUserDelete.Label = "gtk-delete";
		this.hbuttonboxUsers.Add (this.buttonUserDelete);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxUsers [this.buttonUserDelete]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.vboxUsers.Add (this.hbuttonboxUsers);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxUsers [this.hbuttonboxUsers]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vboxUsers.Gtk.Box+BoxChild
		this.vboxUserEdit = new global::Gtk.VBox ();
		this.vboxUserEdit.Name = "vboxUserEdit";
		this.vboxUserEdit.BorderWidth = ((uint)(2));
		// Container child vboxUserEdit.Gtk.Box+BoxChild
		this.labelID = new global::Gtk.Label ();
		this.labelID.Name = "labelID";
		this.labelID.LabelProp = global::Mono.Unix.Catalog.GetString ("ID");
		this.vboxUserEdit.Add (this.labelID);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vboxUserEdit [this.labelID]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vboxUserEdit.Gtk.Box+BoxChild
		this.entryUserEditID = new global::Gtk.Entry ();
		this.entryUserEditID.CanFocus = true;
		this.entryUserEditID.Name = "entryUserEditID";
		this.entryUserEditID.IsEditable = false;
		this.entryUserEditID.InvisibleChar = '●';
		this.vboxUserEdit.Add (this.entryUserEditID);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxUserEdit [this.entryUserEditID]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vboxUserEdit.Gtk.Box+BoxChild
		this.labelUsername = new global::Gtk.Label ();
		this.labelUsername.Name = "labelUsername";
		this.labelUsername.LabelProp = global::Mono.Unix.Catalog.GetString ("Username");
		this.vboxUserEdit.Add (this.labelUsername);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxUserEdit [this.labelUsername]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vboxUserEdit.Gtk.Box+BoxChild
		this.entryUserEditUsername = new global::Gtk.Entry ();
		this.entryUserEditUsername.CanFocus = true;
		this.entryUserEditUsername.Name = "entryUserEditUsername";
		this.entryUserEditUsername.IsEditable = true;
		this.entryUserEditUsername.InvisibleChar = '●';
		this.vboxUserEdit.Add (this.entryUserEditUsername);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vboxUserEdit [this.entryUserEditUsername]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vboxUserEdit.Gtk.Box+BoxChild
		this.labelEmail = new global::Gtk.Label ();
		this.labelEmail.Name = "labelEmail";
		this.labelEmail.LabelProp = global::Mono.Unix.Catalog.GetString ("E-mail");
		this.vboxUserEdit.Add (this.labelEmail);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxUserEdit [this.labelEmail]));
		w14.Position = 4;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vboxUserEdit.Gtk.Box+BoxChild
		this.entryUserEditEmail = new global::Gtk.Entry ();
		this.entryUserEditEmail.CanFocus = true;
		this.entryUserEditEmail.Name = "entryUserEditEmail";
		this.entryUserEditEmail.IsEditable = true;
		this.entryUserEditEmail.InvisibleChar = '●';
		this.vboxUserEdit.Add (this.entryUserEditEmail);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vboxUserEdit [this.entryUserEditEmail]));
		w15.Position = 5;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vboxUserEdit.Gtk.Box+BoxChild
		this.labelPassword = new global::Gtk.Label ();
		this.labelPassword.Name = "labelPassword";
		this.labelPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("Password");
		this.vboxUserEdit.Add (this.labelPassword);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vboxUserEdit [this.labelPassword]));
		w16.Position = 6;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vboxUserEdit.Gtk.Box+BoxChild
		this.entryUserEditPassword = new global::Gtk.Entry ();
		this.entryUserEditPassword.CanFocus = true;
		this.entryUserEditPassword.Name = "entryUserEditPassword";
		this.entryUserEditPassword.IsEditable = true;
		this.entryUserEditPassword.InvisibleChar = '●';
		this.vboxUserEdit.Add (this.entryUserEditPassword);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxUserEdit [this.entryUserEditPassword]));
		w17.Position = 7;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vboxUserEdit.Gtk.Box+BoxChild
		this.hbuttonboxUserEdit = new global::Gtk.HButtonBox ();
		this.hbuttonboxUserEdit.Name = "hbuttonboxUserEdit";
		// Container child hbuttonboxUserEdit.Gtk.ButtonBox+ButtonBoxChild
		this.buttonUserEditCancel = new global::Gtk.Button ();
		this.buttonUserEditCancel.CanFocus = true;
		this.buttonUserEditCancel.Name = "buttonUserEditCancel";
		this.buttonUserEditCancel.UseStock = true;
		this.buttonUserEditCancel.UseUnderline = true;
		this.buttonUserEditCancel.Label = "gtk-cancel";
		this.hbuttonboxUserEdit.Add (this.buttonUserEditCancel);
		global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxUserEdit [this.buttonUserEditCancel]));
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbuttonboxUserEdit.Gtk.ButtonBox+ButtonBoxChild
		this.buttonUserEditOK = new global::Gtk.Button ();
		this.buttonUserEditOK.CanFocus = true;
		this.buttonUserEditOK.Name = "buttonUserEditOK";
		this.buttonUserEditOK.UseStock = true;
		this.buttonUserEditOK.UseUnderline = true;
		this.buttonUserEditOK.Label = "gtk-ok";
		this.hbuttonboxUserEdit.Add (this.buttonUserEditOK);
		global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxUserEdit [this.buttonUserEditOK]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.vboxUserEdit.Add (this.hbuttonboxUserEdit);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vboxUserEdit [this.hbuttonboxUserEdit]));
		w20.Position = 8;
		w20.Expand = false;
		w20.Fill = false;
		this.vboxUsers.Add (this.vboxUserEdit);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vboxUsers [this.vboxUserEdit]));
		w21.Position = 3;
		w21.Expand = false;
		w21.Fill = false;
		this.hbox1.Add (this.vboxUsers);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vboxUsers]));
		w22.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vboxPosts = new global::Gtk.VBox ();
		this.vboxPosts.Name = "vboxPosts";
		this.vboxPosts.Spacing = 6;
		// Container child vboxPosts.Gtk.Box+BoxChild
		this.labelPosts = new global::Gtk.Label ();
		this.labelPosts.Name = "labelPosts";
		this.labelPosts.LabelProp = global::Mono.Unix.Catalog.GetString ("Posts");
		this.vboxPosts.Add (this.labelPosts);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vboxPosts [this.labelPosts]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vboxPosts.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.nodeviewPosts = new global::Gtk.NodeView ();
		this.nodeviewPosts.CanFocus = true;
		this.nodeviewPosts.Name = "nodeviewPosts";
		this.GtkScrolledWindow1.Add (this.nodeviewPosts);
		this.vboxPosts.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vboxPosts [this.GtkScrolledWindow1]));
		w25.Position = 1;
		// Container child vboxPosts.Gtk.Box+BoxChild
		this.hbuttonboxPosts = new global::Gtk.HButtonBox ();
		this.hbuttonboxPosts.Name = "hbuttonboxPosts";
		// Container child hbuttonboxPosts.Gtk.ButtonBox+ButtonBoxChild
		this.buttonPostAdd = new global::Gtk.Button ();
		this.buttonPostAdd.CanFocus = true;
		this.buttonPostAdd.Name = "buttonPostAdd";
		this.buttonPostAdd.UseStock = true;
		this.buttonPostAdd.UseUnderline = true;
		this.buttonPostAdd.Label = "gtk-add";
		this.hbuttonboxPosts.Add (this.buttonPostAdd);
		global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxPosts [this.buttonPostAdd]));
		w26.Expand = false;
		w26.Fill = false;
		// Container child hbuttonboxPosts.Gtk.ButtonBox+ButtonBoxChild
		this.buttonPostEdit = new global::Gtk.Button ();
		this.buttonPostEdit.CanFocus = true;
		this.buttonPostEdit.Name = "buttonPostEdit";
		this.buttonPostEdit.UseStock = true;
		this.buttonPostEdit.UseUnderline = true;
		this.buttonPostEdit.Label = "gtk-edit";
		this.hbuttonboxPosts.Add (this.buttonPostEdit);
		global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxPosts [this.buttonPostEdit]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbuttonboxPosts.Gtk.ButtonBox+ButtonBoxChild
		this.buttonPostDelete = new global::Gtk.Button ();
		this.buttonPostDelete.CanFocus = true;
		this.buttonPostDelete.Name = "buttonPostDelete";
		this.buttonPostDelete.UseStock = true;
		this.buttonPostDelete.UseUnderline = true;
		this.buttonPostDelete.Label = "gtk-delete";
		this.hbuttonboxPosts.Add (this.buttonPostDelete);
		global::Gtk.ButtonBox.ButtonBoxChild w28 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxPosts [this.buttonPostDelete]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.vboxPosts.Add (this.hbuttonboxPosts);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vboxPosts [this.hbuttonboxPosts]));
		w29.Position = 2;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vboxPosts.Gtk.Box+BoxChild
		this.vboxPostEdit = new global::Gtk.VBox ();
		this.vboxPostEdit.Name = "vboxPostEdit";
		this.vboxPostEdit.BorderWidth = ((uint)(2));
		// Container child vboxPostEdit.Gtk.Box+BoxChild
		this.labelID1 = new global::Gtk.Label ();
		this.labelID1.Name = "labelID1";
		this.labelID1.LabelProp = global::Mono.Unix.Catalog.GetString ("ID");
		this.vboxPostEdit.Add (this.labelID1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vboxPostEdit [this.labelID1]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child vboxPostEdit.Gtk.Box+BoxChild
		this.entryPostEditID = new global::Gtk.Entry ();
		this.entryPostEditID.CanFocus = true;
		this.entryPostEditID.Name = "entryPostEditID";
		this.entryPostEditID.IsEditable = false;
		this.entryPostEditID.InvisibleChar = '●';
		this.vboxPostEdit.Add (this.entryPostEditID);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vboxPostEdit [this.entryPostEditID]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		// Container child vboxPostEdit.Gtk.Box+BoxChild
		this.labelAuthorID = new global::Gtk.Label ();
		this.labelAuthorID.Name = "labelAuthorID";
		this.labelAuthorID.LabelProp = global::Mono.Unix.Catalog.GetString ("Author ID");
		this.vboxPostEdit.Add (this.labelAuthorID);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vboxPostEdit [this.labelAuthorID]));
		w32.Position = 2;
		w32.Expand = false;
		w32.Fill = false;
		// Container child vboxPostEdit.Gtk.Box+BoxChild
		this.entryPostEditAuthor = new global::Gtk.Entry ();
		this.entryPostEditAuthor.CanFocus = true;
		this.entryPostEditAuthor.Name = "entryPostEditAuthor";
		this.entryPostEditAuthor.IsEditable = true;
		this.entryPostEditAuthor.InvisibleChar = '●';
		this.vboxPostEdit.Add (this.entryPostEditAuthor);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vboxPostEdit [this.entryPostEditAuthor]));
		w33.Position = 3;
		w33.Expand = false;
		w33.Fill = false;
		// Container child vboxPostEdit.Gtk.Box+BoxChild
		this.labelPostEditTags = new global::Gtk.Label ();
		this.labelPostEditTags.Name = "labelPostEditTags";
		this.labelPostEditTags.LabelProp = global::Mono.Unix.Catalog.GetString ("Tags (comma-separated)");
		this.vboxPostEdit.Add (this.labelPostEditTags);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vboxPostEdit [this.labelPostEditTags]));
		w34.Position = 4;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vboxPostEdit.Gtk.Box+BoxChild
		this.entryPostEditTags = new global::Gtk.Entry ();
		this.entryPostEditTags.CanFocus = true;
		this.entryPostEditTags.Name = "entryPostEditTags";
		this.entryPostEditTags.IsEditable = true;
		this.entryPostEditTags.InvisibleChar = '●';
		this.vboxPostEdit.Add (this.entryPostEditTags);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vboxPostEdit [this.entryPostEditTags]));
		w35.Position = 5;
		w35.Expand = false;
		w35.Fill = false;
		// Container child vboxPostEdit.Gtk.Box+BoxChild
		this.labelTitle = new global::Gtk.Label ();
		this.labelTitle.Name = "labelTitle";
		this.labelTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Title");
		this.vboxPostEdit.Add (this.labelTitle);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vboxPostEdit [this.labelTitle]));
		w36.Position = 6;
		w36.Expand = false;
		w36.Fill = false;
		// Container child vboxPostEdit.Gtk.Box+BoxChild
		this.entryPostEditTitle = new global::Gtk.Entry ();
		this.entryPostEditTitle.CanFocus = true;
		this.entryPostEditTitle.Name = "entryPostEditTitle";
		this.entryPostEditTitle.IsEditable = true;
		this.entryPostEditTitle.InvisibleChar = '●';
		this.vboxPostEdit.Add (this.entryPostEditTitle);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vboxPostEdit [this.entryPostEditTitle]));
		w37.Position = 7;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vboxPostEdit.Gtk.Box+BoxChild
		this.labelText = new global::Gtk.Label ();
		this.labelText.Name = "labelText";
		this.labelText.LabelProp = global::Mono.Unix.Catalog.GetString ("Text");
		this.vboxPostEdit.Add (this.labelText);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vboxPostEdit [this.labelText]));
		w38.Position = 8;
		w38.Expand = false;
		w38.Fill = false;
		// Container child vboxPostEdit.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.textviewPostEditText = new global::Gtk.TextView ();
		this.textviewPostEditText.CanFocus = true;
		this.textviewPostEditText.Name = "textviewPostEditText";
		this.GtkScrolledWindow3.Add (this.textviewPostEditText);
		this.vboxPostEdit.Add (this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vboxPostEdit [this.GtkScrolledWindow3]));
		w40.Position = 9;
		// Container child vboxPostEdit.Gtk.Box+BoxChild
		this.hbuttonboxPostEdit = new global::Gtk.HButtonBox ();
		this.hbuttonboxPostEdit.Name = "hbuttonboxPostEdit";
		// Container child hbuttonboxPostEdit.Gtk.ButtonBox+ButtonBoxChild
		this.buttonPostEditCancel = new global::Gtk.Button ();
		this.buttonPostEditCancel.CanFocus = true;
		this.buttonPostEditCancel.Name = "buttonPostEditCancel";
		this.buttonPostEditCancel.UseStock = true;
		this.buttonPostEditCancel.UseUnderline = true;
		this.buttonPostEditCancel.Label = "gtk-cancel";
		this.hbuttonboxPostEdit.Add (this.buttonPostEditCancel);
		global::Gtk.ButtonBox.ButtonBoxChild w41 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxPostEdit [this.buttonPostEditCancel]));
		w41.Expand = false;
		w41.Fill = false;
		// Container child hbuttonboxPostEdit.Gtk.ButtonBox+ButtonBoxChild
		this.buttonPostEditOK = new global::Gtk.Button ();
		this.buttonPostEditOK.CanFocus = true;
		this.buttonPostEditOK.Name = "buttonPostEditOK";
		this.buttonPostEditOK.UseStock = true;
		this.buttonPostEditOK.UseUnderline = true;
		this.buttonPostEditOK.Label = "gtk-ok";
		this.hbuttonboxPostEdit.Add (this.buttonPostEditOK);
		global::Gtk.ButtonBox.ButtonBoxChild w42 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxPostEdit [this.buttonPostEditOK]));
		w42.Position = 1;
		w42.Expand = false;
		w42.Fill = false;
		this.vboxPostEdit.Add (this.hbuttonboxPostEdit);
		global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vboxPostEdit [this.hbuttonboxPostEdit]));
		w43.Position = 10;
		w43.Expand = false;
		w43.Fill = false;
		this.vboxPosts.Add (this.vboxPostEdit);
		global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vboxPosts [this.vboxPostEdit]));
		w44.Position = 3;
		this.hbox1.Add (this.vboxPosts);
		global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vboxPosts]));
		w45.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vboxTags = new global::Gtk.VBox ();
		this.vboxTags.Name = "vboxTags";
		this.vboxTags.Spacing = 6;
		// Container child vboxTags.Gtk.Box+BoxChild
		this.labelTags = new global::Gtk.Label ();
		this.labelTags.Name = "labelTags";
		this.labelTags.LabelProp = global::Mono.Unix.Catalog.GetString ("Tags");
		this.vboxTags.Add (this.labelTags);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vboxTags [this.labelTags]));
		w46.Position = 0;
		w46.Expand = false;
		w46.Fill = false;
		// Container child vboxTags.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.nodeviewTags = new global::Gtk.NodeView ();
		this.nodeviewTags.CanFocus = true;
		this.nodeviewTags.Name = "nodeviewTags";
		this.GtkScrolledWindow2.Add (this.nodeviewTags);
		this.vboxTags.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vboxTags [this.GtkScrolledWindow2]));
		w48.Position = 1;
		// Container child vboxTags.Gtk.Box+BoxChild
		this.hbuttonboxTags = new global::Gtk.HButtonBox ();
		this.hbuttonboxTags.Name = "hbuttonboxTags";
		// Container child hbuttonboxTags.Gtk.ButtonBox+ButtonBoxChild
		this.buttonTagAdd = new global::Gtk.Button ();
		this.buttonTagAdd.CanFocus = true;
		this.buttonTagAdd.Name = "buttonTagAdd";
		this.buttonTagAdd.UseStock = true;
		this.buttonTagAdd.UseUnderline = true;
		this.buttonTagAdd.Label = "gtk-add";
		this.hbuttonboxTags.Add (this.buttonTagAdd);
		global::Gtk.ButtonBox.ButtonBoxChild w49 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxTags [this.buttonTagAdd]));
		w49.Expand = false;
		w49.Fill = false;
		// Container child hbuttonboxTags.Gtk.ButtonBox+ButtonBoxChild
		this.buttonTagEdit = new global::Gtk.Button ();
		this.buttonTagEdit.CanFocus = true;
		this.buttonTagEdit.Name = "buttonTagEdit";
		this.buttonTagEdit.UseStock = true;
		this.buttonTagEdit.UseUnderline = true;
		this.buttonTagEdit.Label = "gtk-edit";
		this.hbuttonboxTags.Add (this.buttonTagEdit);
		global::Gtk.ButtonBox.ButtonBoxChild w50 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxTags [this.buttonTagEdit]));
		w50.Position = 1;
		w50.Expand = false;
		w50.Fill = false;
		// Container child hbuttonboxTags.Gtk.ButtonBox+ButtonBoxChild
		this.buttonTagDelete = new global::Gtk.Button ();
		this.buttonTagDelete.CanFocus = true;
		this.buttonTagDelete.Name = "buttonTagDelete";
		this.buttonTagDelete.UseStock = true;
		this.buttonTagDelete.UseUnderline = true;
		this.buttonTagDelete.Label = "gtk-delete";
		this.hbuttonboxTags.Add (this.buttonTagDelete);
		global::Gtk.ButtonBox.ButtonBoxChild w51 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxTags [this.buttonTagDelete]));
		w51.Position = 2;
		w51.Expand = false;
		w51.Fill = false;
		this.vboxTags.Add (this.hbuttonboxTags);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vboxTags [this.hbuttonboxTags]));
		w52.Position = 2;
		w52.Expand = false;
		w52.Fill = false;
		// Container child vboxTags.Gtk.Box+BoxChild
		this.vboxTagEdit = new global::Gtk.VBox ();
		this.vboxTagEdit.Name = "vboxTagEdit";
		this.vboxTagEdit.BorderWidth = ((uint)(2));
		// Container child vboxTagEdit.Gtk.Box+BoxChild
		this.labelID2 = new global::Gtk.Label ();
		this.labelID2.Name = "labelID2";
		this.labelID2.LabelProp = global::Mono.Unix.Catalog.GetString ("ID");
		this.vboxTagEdit.Add (this.labelID2);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vboxTagEdit [this.labelID2]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		// Container child vboxTagEdit.Gtk.Box+BoxChild
		this.entryTagEditID = new global::Gtk.Entry ();
		this.entryTagEditID.CanFocus = true;
		this.entryTagEditID.Name = "entryTagEditID";
		this.entryTagEditID.IsEditable = false;
		this.entryTagEditID.InvisibleChar = '●';
		this.vboxTagEdit.Add (this.entryTagEditID);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vboxTagEdit [this.entryTagEditID]));
		w54.Position = 1;
		w54.Expand = false;
		w54.Fill = false;
		// Container child vboxTagEdit.Gtk.Box+BoxChild
		this.labelTitle1 = new global::Gtk.Label ();
		this.labelTitle1.Name = "labelTitle1";
		this.labelTitle1.LabelProp = global::Mono.Unix.Catalog.GetString ("Title");
		this.vboxTagEdit.Add (this.labelTitle1);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vboxTagEdit [this.labelTitle1]));
		w55.Position = 2;
		w55.Expand = false;
		w55.Fill = false;
		// Container child vboxTagEdit.Gtk.Box+BoxChild
		this.entryTagEditTitle = new global::Gtk.Entry ();
		this.entryTagEditTitle.CanFocus = true;
		this.entryTagEditTitle.Name = "entryTagEditTitle";
		this.entryTagEditTitle.IsEditable = true;
		this.entryTagEditTitle.InvisibleChar = '●';
		this.vboxTagEdit.Add (this.entryTagEditTitle);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vboxTagEdit [this.entryTagEditTitle]));
		w56.Position = 3;
		w56.Expand = false;
		w56.Fill = false;
		// Container child vboxTagEdit.Gtk.Box+BoxChild
		this.hbuttonboxTagEdit = new global::Gtk.HButtonBox ();
		this.hbuttonboxTagEdit.Name = "hbuttonboxTagEdit";
		// Container child hbuttonboxTagEdit.Gtk.ButtonBox+ButtonBoxChild
		this.buttonTagEditCancel = new global::Gtk.Button ();
		this.buttonTagEditCancel.CanFocus = true;
		this.buttonTagEditCancel.Name = "buttonTagEditCancel";
		this.buttonTagEditCancel.UseStock = true;
		this.buttonTagEditCancel.UseUnderline = true;
		this.buttonTagEditCancel.Label = "gtk-cancel";
		this.hbuttonboxTagEdit.Add (this.buttonTagEditCancel);
		global::Gtk.ButtonBox.ButtonBoxChild w57 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxTagEdit [this.buttonTagEditCancel]));
		w57.Expand = false;
		w57.Fill = false;
		// Container child hbuttonboxTagEdit.Gtk.ButtonBox+ButtonBoxChild
		this.buttonTagEditOK = new global::Gtk.Button ();
		this.buttonTagEditOK.CanFocus = true;
		this.buttonTagEditOK.Name = "buttonTagEditOK";
		this.buttonTagEditOK.UseStock = true;
		this.buttonTagEditOK.UseUnderline = true;
		this.buttonTagEditOK.Label = "gtk-ok";
		this.hbuttonboxTagEdit.Add (this.buttonTagEditOK);
		global::Gtk.ButtonBox.ButtonBoxChild w58 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonboxTagEdit [this.buttonTagEditOK]));
		w58.Position = 1;
		w58.Expand = false;
		w58.Fill = false;
		this.vboxTagEdit.Add (this.hbuttonboxTagEdit);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vboxTagEdit [this.hbuttonboxTagEdit]));
		w59.Position = 4;
		w59.Expand = false;
		w59.Fill = false;
		this.vboxTags.Add (this.vboxTagEdit);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vboxTags [this.vboxTagEdit]));
		w60.Position = 3;
		w60.Expand = false;
		w60.Fill = false;
		this.hbox1.Add (this.vboxTags);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vboxTags]));
		w61.Position = 2;
		this.vboxMain.Add (this.hbox1);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vboxMain [this.hbox1]));
		w62.Position = 1;
		this.Add (this.vboxMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 979;
		this.DefaultHeight = 534;
		this.vboxUserEdit.Hide ();
		this.vboxPostEdit.Hide ();
		this.vboxTagEdit.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonUpdate.Clicked += new global::System.EventHandler (this.OnButtonUpdateClicked);
		this.buttonUserAdd.Clicked += new global::System.EventHandler (this.OnButtonUserAddClicked);
		this.buttonUserEdit.Clicked += new global::System.EventHandler (this.OnButtonUserEditClicked);
		this.buttonUserDelete.Clicked += new global::System.EventHandler (this.OnButtonUserDeleteClicked);
		this.buttonUserEditCancel.Clicked += new global::System.EventHandler (this.OnButtonUserEditCancelClicked);
		this.buttonUserEditOK.Clicked += new global::System.EventHandler (this.OnButtonUserEditOKClicked);
		this.buttonPostAdd.Clicked += new global::System.EventHandler (this.OnButtonPostAddClicked);
		this.buttonPostEdit.Clicked += new global::System.EventHandler (this.OnButtonPostEditClicked);
		this.buttonPostDelete.Clicked += new global::System.EventHandler (this.OnButtonPostDeleteClicked);
		this.buttonPostEditCancel.Clicked += new global::System.EventHandler (this.OnButtonPostEditCancelClicked);
		this.buttonPostEditOK.Clicked += new global::System.EventHandler (this.OnButtonPostEditOKClicked);
		this.buttonTagAdd.Clicked += new global::System.EventHandler (this.OnButtonTagAddClicked);
		this.buttonTagEdit.Clicked += new global::System.EventHandler (this.OnButtonTagEditClicked);
		this.buttonTagDelete.Clicked += new global::System.EventHandler (this.OnButtonTagDeleteClicked);
		this.buttonTagEditCancel.Clicked += new global::System.EventHandler (this.OnButtonTagEditCancelClicked);
		this.buttonTagEditOK.Clicked += new global::System.EventHandler (this.OnButtonTagEditOKClicked);
	}
}
